# Generated by Django 3.0.8 on 2021-08-17 02:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_option_name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_plate_name', models.CharField(max_length=30)),
                ('menu_plate_type', models.CharField(choices=[(1, 'Entrance plate'), (2, 'Bottom plate'), (3, 'Dessert')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappMessageEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yumminess.Employee')),
                ('whatsapp_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yumminess.WhatsappMessage')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_customization', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yumminess.Employee')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yumminess.MenuOption')),
            ],
        ),
        migrations.AddField(
            model_name='menuoption',
            name='menu_option_bottom_plate',
            field=models.ForeignKey(limit_choices_to={'menu_plate_type: 2'}, on_delete=django.db.models.deletion.CASCADE, related_name='menu_option_bottom_plate', to='yumminess.MenuPlate'),
        ),
        migrations.AddField(
            model_name='menuoption',
            name='menu_option_dessert_plate',
            field=models.ForeignKey(limit_choices_to={'menu_plate_type: 3'}, on_delete=django.db.models.deletion.CASCADE, related_name='menu_option_dessert_plate', to='yumminess.MenuPlate'),
        ),
        migrations.AddField(
            model_name='menuoption',
            name='menu_option_entrance_plate',
            field=models.ForeignKey(limit_choices_to={'menu_plate_type: 1'}, on_delete=django.db.models.deletion.CASCADE, related_name='menu_option_entrance_plate', to='yumminess.MenuPlate'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('d535e5f3-120e-4ddc-b18f-b9d793d8e28f'))),
                ('menu_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_options', models.ManyToManyField(to='yumminess.MenuOption')),
            ],
        ),
    ]
